/*
 * Calculator API
 *
 * A REST API for performing arithmetic operations. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.IO;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.OpenApi.Models;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Serialization;
using IO.Swagger.Filters;
using IO.Swagger.Extensions;

namespace IO.Swagger
{
    /// <summary>
    /// Startup
    /// </summary>
    public class Startup
    {
        private readonly IWebHostEnvironment _hostingEnv;

        private IConfiguration Configuration { get; }

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="env"></param>
        /// <param name="configuration"></param>
        public Startup(IWebHostEnvironment env, IConfiguration configuration)
        {
            _hostingEnv = env;
            Configuration = configuration;
        }

        /// <summary>
        /// Configures services for the application.
        /// Registers logging, infrastructure (MongoDB, Redis), authentication (JWT),
        /// exception handling, application services, and MVC with Swagger.
        /// </summary>
        /// <param name="services">Service collection to configure</param>
        public void ConfigureServices(IServiceCollection services)
        {
            // Configure Serilog logging
            LoggingExtensions.LoadLoggingConfigurations(_hostingEnv);
            
            // Load and configure infrastructure options (MongoDB, Redis, JWT)
            services.LoadMongoOptions(Configuration);
            services.LoadRedisOptions(Configuration);
            services.LoadJwtOptions(Configuration);
            
            // Register global exception handler
            services.AddGlobalExceptionHandler();
            
            // Register all application services (repositories, business services, security)
            services.AddApplicationServices();
            
            // Add framework services.
            services
                .AddMvc(options =>
                {
                    options.InputFormatters
                        .RemoveType<Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter>();
                    options.OutputFormatters
                        .RemoveType<Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter>();
                })
                .AddNewtonsoftJson(opts =>
                {
                    opts.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                    opts.SerializerSettings.Converters.Add(new StringEnumConverter(new CamelCaseNamingStrategy()));
                })
                .AddXmlSerializerFormatters();

            services
                .AddSwaggerGen(c =>
                {
                    c.SwaggerDoc("1.0.0", new OpenApiInfo
                    {
                        Version = "1.0.0",
                        Title = "Calculator API",
                        Description = "Calculator API (ASP.NET Core 8.0)",
                        Contact = new OpenApiContact()
                        {
                           Name = "API Support",
                           Url = new Uri("https://github.com/tamir303"),
                           Email = ""
                        }
                    });

                    // Add Bearer Token Authentication
                    c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
                    {
                        Description = "JWT Authorization header using the Bearer scheme. \r\n\r\n Enter 'Bearer' [space] and then your token in the text input below.\r\n\r\nExample: \"Bearer 12345abcdef\"",
                        Name = "Authorization",
                        In = ParameterLocation.Header,
                        Type = SecuritySchemeType.ApiKey,
                        Scheme = "Bearer"
                    });

                    c.AddSecurityRequirement(new OpenApiSecurityRequirement()
                    {
                        {
                            new OpenApiSecurityScheme
                            {
                                Reference = new OpenApiReference
                                {
                                    Type = ReferenceType.SecurityScheme,
                                    Id = "Bearer"
                                },
                                Scheme = "oauth2",
                                Name = "Bearer",
                                In = ParameterLocation.Header,
                            },
                            new List<string>()
                        }
                    });

                    c.CustomSchemaIds(type => type.FullName.Replace('+', '.'));
                    c.IncludeXmlComments($"{AppContext.BaseDirectory}{Path.DirectorySeparatorChar}{_hostingEnv.ApplicationName}.xml");
                    
                    // Sets the basePath property in the Swagger document generated
                    c.DocumentFilter<BasePathFilter>("/v1");

                    c.OperationFilter<GeneratePathParamsValidationFilter>();
                });

            services.AddSwaggerGenNewtonsoftSupport();
        }

        /// <summary>
        /// Configures the HTTP request pipeline.
        /// Sets up middleware for exception handling, routing, static files,
        /// authorization, Swagger documentation, HTTPS redirection, and endpoint routing.
        /// </summary>
        /// <param name="app">Application builder</param>
        /// <param name="env">Hosting environment</param>
        /// <param name="loggerFactory">Logger factory</param>
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
        {
            // Use global exception handler (must be early in pipeline)
            app.UseGlobalExceptionHandler();
            
            app.UseRouting();

            app.UseStaticFiles();

            app.UseAuthorization();
            
            // Disable swagger on production
            if (!env.IsProduction())
            {
                app.UseSwagger();
                app.UseSwaggerUI(c => { c.SwaggerEndpoint("/swagger/1.0.0/swagger.json", "Calculator API"); });
            }

            app.UseHttpsRedirection();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
}
